module mdio_ctrl #(
    parameter int CLK_FREQ_HZ = 100_000_000,
    parameter int MDC_FREQ_HZ = 2_500_000
) (
    input  logic        clk,
    input  logic        rst,

    // ── MDIO Physical Interface ───────────────────────────────────────
    output logic        mdc,
    output logic        mdio_out,
    output logic        mdio_oe,
    input  logic        mdio_in,

    // ── Interrupt ─────────────────────────────────────────────────────
    output logic        irq,

    // ── Register Interface (AXI4-Lite subordinate, 5-bit addr) ────────
    // Write Address
    output logic        reg_axi_awready,
    input  logic        reg_axi_awvalid,
    input  logic [4:0]  reg_axi_awaddr,
    input  logic [2:0]  reg_axi_awprot,

    // Write Data
    output logic        reg_axi_wready,
    input  logic        reg_axi_wvalid,
    input  logic [31:0] reg_axi_wdata,
    input  logic [3:0]  reg_axi_wstrb,

    // Write Response
    input  logic        reg_axi_bready,
    output logic        reg_axi_bvalid,
    output logic [1:0]  reg_axi_bresp,

    // Read Address
    output logic        reg_axi_arready,
    input  logic        reg_axi_arvalid,
    input  logic [4:0]  reg_axi_araddr,
    input  logic [2:0]  reg_axi_arprot,

    // Read Data
    input  logic        reg_axi_rready,
    output logic        reg_axi_rvalid,
    output logic [31:0] reg_axi_rdata,
    output logic [1:0]  reg_axi_rresp
);

    // =====================================================================
    //  Constants
    // =====================================================================

    localparam int MDC_DIV = (CLK_FREQ_HZ / (2 * MDC_FREQ_HZ)) - 1;

    // =====================================================================
    //  Internal Control / Status signals (driven by register block)
    // =====================================================================

    logic        ctrl_go;
    logic        ctrl_wr_nrd;
    logic [4:0]  ctrl_prtad;
    logic [4:0]  ctrl_devad;
    logic [15:0] ctrl_reg_addr;
    logic [15:0] ctrl_wrdata;

    logic        status_busy;
    logic        status_done;
    logic        status_error;
    logic [15:0] captured_rddata;

    // =====================================================================
    //  AXI4-Lite Register Block (generated by PeakRDL)
    // =====================================================================

    mdio_ctrl_regs_pkg::mdio_ctrl_regs__in_t  regs_hwif_in;
    mdio_ctrl_regs_pkg::mdio_ctrl_regs__out_t regs_hwif_out;

    mdio_ctrl_regs u_regs (
        .clk            (clk),
        .rst            (rst),
        // AXI4-Lite — map reg_axi_* to s_axil_*
        .s_axil_awvalid (reg_axi_awvalid),
        .s_axil_awready (reg_axi_awready),
        .s_axil_awaddr  (reg_axi_awaddr),
        .s_axil_awprot  (reg_axi_awprot),
        .s_axil_wvalid  (reg_axi_wvalid),
        .s_axil_wready  (reg_axi_wready),
        .s_axil_wdata   (reg_axi_wdata),
        .s_axil_wstrb   (reg_axi_wstrb),
        .s_axil_bvalid  (reg_axi_bvalid),
        .s_axil_bready  (reg_axi_bready),
        .s_axil_bresp   (reg_axi_bresp),
        .s_axil_arvalid (reg_axi_arvalid),
        .s_axil_arready (reg_axi_arready),
        .s_axil_araddr  (reg_axi_araddr),
        .s_axil_arprot  (reg_axi_arprot),
        .s_axil_rvalid  (reg_axi_rvalid),
        .s_axil_rready  (reg_axi_rready),
        .s_axil_rdata   (reg_axi_rdata),
        .s_axil_rresp   (reg_axi_rresp),
        // Hardware interface
        .hwif_in        (regs_hwif_in),
        .hwif_out       (regs_hwif_out)
    );

    // Connect hwif_out → internal control signals
    assign ctrl_go       = regs_hwif_out.CTRL.go.value;
    assign ctrl_wr_nrd   = regs_hwif_out.CTRL.wr_nrd.value;
    assign ctrl_prtad    = regs_hwif_out.PHY_ADDR.prtad.value;
    assign ctrl_devad    = regs_hwif_out.PHY_ADDR.devad.value;
    assign ctrl_reg_addr = regs_hwif_out.REG_ADDR.addr.value;
    assign ctrl_wrdata   = regs_hwif_out.WRDATA.data.value;

    // Connect internal status signals → hwif_in
    assign regs_hwif_in.RDDATA.data.next       = captured_rddata;
    assign regs_hwif_in.STATUS.busy.next       = status_busy;
    assign regs_hwif_in.STATUS.done.hwset      = status_done;
    assign regs_hwif_in.STATUS.error.hwset     = status_error;
    assign regs_hwif_in.IRQ_STATUS.done.hwset  = status_done;
    assign regs_hwif_in.IRQ_STATUS.error.hwset = status_error;

    // =====================================================================
    //  Interrupt Output
    // =====================================================================

    assign irq = (regs_hwif_out.IRQ_STATUS.done.value  & regs_hwif_out.IRQ_EN.done_en.value)
               | (regs_hwif_out.IRQ_STATUS.error.value & regs_hwif_out.IRQ_EN.error_en.value);

    // =====================================================================
    //  MDC Clock Generation
    // =====================================================================

    logic [$clog2(MDC_DIV+1)-1:0] mdc_cnt;
    logic mdc_rise;
    logic mdc_fall;
    logic mdc_en;       // Gate MDC toggling — only active during transaction
    logic mdc_int;      // Internal MDC state

    always_ff @(posedge clk) begin
        if (rst) begin
            mdc_cnt  <= '0;
            mdc_int  <= 1'b0;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end else if (!mdc_en) begin
            mdc_cnt  <= '0;
            mdc_int  <= 1'b0;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end else if (mdc_cnt == MDC_DIV[$clog2(MDC_DIV+1)-1:0]) begin
            mdc_cnt  <= '0;
            mdc_int  <= ~mdc_int;
            mdc_rise <= ~mdc_int;
            mdc_fall <=  mdc_int;
        end else begin
            mdc_cnt  <= mdc_cnt + 1;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end
    end

    assign mdc = mdc_int;

    // =====================================================================
    //  MDIO Clause 45 FSM
    // =====================================================================

    typedef enum logic [3:0] {
        ST_IDLE,
        ST_ADDR_PRE,
        ST_ADDR_ST,
        ST_ADDR_OP,
        ST_ADDR_PRTAD,
        ST_ADDR_DEVAD,
        ST_ADDR_TA,
        ST_ADDR_DATA,
        ST_TURNAROUND,
        ST_RW_PRE,
        ST_RW_ST,
        ST_RW_OP,
        ST_RW_PRTAD,
        ST_RW_DEVAD,
        ST_RW_TA,
        ST_RW_DATA
    } mdio_state_t;

    mdio_state_t state;

    logic [5:0]  bit_cnt;
    logic [31:0] shift_reg;
    logic        is_write;     // Latched write/read direction
    logic        ta_error;

    // ── FSM next-state + output logic ─────────────────────────────────
    always_ff @(posedge clk) begin
        if (rst) begin
            state          <= ST_IDLE;
            bit_cnt        <= '0;
            shift_reg      <= '0;
            is_write       <= 1'b0;
            ta_error       <= 1'b0;
            mdio_oe        <= 1'b0;
            mdio_out       <= 1'b1;
            mdc_en         <= 1'b0;
            captured_rddata <= '0;
            status_busy    <= 1'b0;
            status_done    <= 1'b0;
            status_error   <= 1'b0;
        end else begin
            // Default: clear single-cycle pulses
            status_done  <= 1'b0;
            status_error <= 1'b0;

            case (state)
                // ─────────────────────────────────────────────────────
                ST_IDLE: begin
                    mdio_oe  <= 1'b0;
                    mdio_out <= 1'b1;
                    mdc_en   <= 1'b0;
                    if (ctrl_go) begin
                        is_write    <= ctrl_wr_nrd;
                        ta_error    <= 1'b0;
                        status_busy <= 1'b1;
                        // Load preamble: 32 ones
                        shift_reg   <= 32'hFFFF_FFFF;
                        bit_cnt     <= 6'd31;
                        mdio_oe     <= 1'b1;
                        mdio_out    <= 1'b1;
                        mdc_en      <= 1'b1;
                        state       <= ST_ADDR_PRE;
                    end
                end

                // ── Frame 1: Address Frame ───────────────────────────
                ST_ADDR_PRE: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load ST = 2'b00
                            shift_reg <= {2'b00, 30'd0};
                            bit_cnt   <= 6'd1;
                            state     <= ST_ADDR_ST;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_ST: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load OP = 2'b00 (address)
                            shift_reg <= {2'b00, 30'd0};
                            bit_cnt   <= 6'd1;
                            state     <= ST_ADDR_OP;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_OP: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load PRTAD (5 bits)
                            shift_reg <= {ctrl_prtad, 27'd0};
                            bit_cnt   <= 6'd4;
                            state     <= ST_ADDR_PRTAD;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_PRTAD: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load DEVAD (5 bits)
                            shift_reg <= {ctrl_devad, 27'd0};
                            bit_cnt   <= 6'd4;
                            state     <= ST_ADDR_DEVAD;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_DEVAD: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load TA = 2'b10
                            shift_reg <= {2'b10, 30'd0};
                            bit_cnt   <= 6'd1;
                            state     <= ST_ADDR_TA;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_TA: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load REG_ADDR (16 bits)
                            shift_reg <= {ctrl_reg_addr, 16'd0};
                            bit_cnt   <= 6'd15;
                            state     <= ST_ADDR_DATA;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_ADDR_DATA: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Inter-frame turnaround: 1 idle cycle
                            mdio_oe <= 1'b0;
                            state   <= ST_TURNAROUND;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                // ── Inter-frame gap ──────────────────────────────────
                ST_TURNAROUND: begin
                    if (mdc_fall) begin
                        // Load preamble for frame 2: 32 ones
                        shift_reg <= 32'hFFFF_FFFF;
                        bit_cnt   <= 6'd31;
                        mdio_oe   <= 1'b1;
                        mdio_out  <= 1'b1;
                        state     <= ST_RW_PRE;
                    end
                end

                // ── Frame 2: Read/Write Frame ────────────────────────
                ST_RW_PRE: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load ST = 2'b00
                            shift_reg <= {2'b00, 30'd0};
                            bit_cnt   <= 6'd1;
                            state     <= ST_RW_ST;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_RW_ST: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load OP: read=2'b11, write=2'b01
                            shift_reg <= {(is_write ? 2'b01 : 2'b11), 30'd0};
                            bit_cnt   <= 6'd1;
                            state     <= ST_RW_OP;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_RW_OP: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load PRTAD (5 bits)
                            shift_reg <= {ctrl_prtad, 27'd0};
                            bit_cnt   <= 6'd4;
                            state     <= ST_RW_PRTAD;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_RW_PRTAD: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            // Load DEVAD (5 bits)
                            shift_reg <= {ctrl_devad, 27'd0};
                            bit_cnt   <= 6'd4;
                            state     <= ST_RW_DEVAD;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_RW_DEVAD: begin
                    if (mdc_fall) begin
                        mdio_out  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        if (bit_cnt == 0) begin
                            if (is_write) begin
                                // Write TA = 2'b10, we drive
                                shift_reg <= {2'b10, 30'd0};
                                bit_cnt   <= 6'd1;
                                mdio_oe   <= 1'b1;
                            end else begin
                                // Read TA: release bus, PHY drives
                                shift_reg <= '0;
                                bit_cnt   <= 6'd1;
                                mdio_oe   <= 1'b0;
                            end
                            state <= ST_RW_TA;
                        end else begin
                            bit_cnt <= bit_cnt - 1;
                        end
                    end
                end

                ST_RW_TA: begin
                    if (is_write) begin
                        // Write TA: we drive 1 then 0
                        if (mdc_fall) begin
                            mdio_out  <= shift_reg[31];
                            shift_reg <= {shift_reg[30:0], 1'b0};
                            if (bit_cnt == 0) begin
                                // Load write data (16 bits)
                                shift_reg <= {ctrl_wrdata, 16'd0};
                                bit_cnt   <= 6'd15;
                                state     <= ST_RW_DATA;
                            end else begin
                                bit_cnt <= bit_cnt - 1;
                            end
                        end
                    end else begin
                        // Read TA: PHY drives, we sample
                        if (mdc_rise) begin
                            if (bit_cnt == 0) begin
                                // Second TA bit — PHY should drive 0
                                if (mdio_in != 1'b0)
                                    ta_error <= 1'b1;
                                bit_cnt <= 6'd15;
                                state   <= ST_RW_DATA;
                            end else begin
                                bit_cnt <= bit_cnt - 1;
                            end
                        end
                    end
                end

                ST_RW_DATA: begin
                    if (is_write) begin
                        // Write: shift out data on falling edge
                        if (mdc_fall) begin
                            mdio_out  <= shift_reg[31];
                            shift_reg <= {shift_reg[30:0], 1'b0};
                            if (bit_cnt == 0) begin
                                // Transaction complete
                                status_busy <= 1'b0;
                                status_done <= 1'b1;
                                mdio_oe     <= 1'b0;
                                mdc_en      <= 1'b0;
                                state       <= ST_IDLE;
                            end else begin
                                bit_cnt <= bit_cnt - 1;
                            end
                        end
                    end else begin
                        // Read: shift in data on rising edge
                        if (mdc_rise) begin
                            captured_rddata <= {captured_rddata[14:0], mdio_in};
                            if (bit_cnt == 0) begin
                                // Transaction complete
                                status_busy  <= 1'b0;
                                status_done  <= 1'b1;
                                status_error <= ta_error;
                                mdc_en       <= 1'b0;
                                state        <= ST_IDLE;
                            end else begin
                                bit_cnt <= bit_cnt - 1;
                            end
                        end
                    end
                end

                default: state <= ST_IDLE;
            endcase
        end
    end

endmodule
