module axi_mdio #(
    parameter int CLK_FREQ_HZ = 100_000_000,
    parameter int MDC_FREQ_HZ = 2_500_000
) (
    input  logic        clk,
    input  logic        rst,

    // ── MDIO Physical Interface ───────────────────────────────────────
    output logic        mdc,
    output logic        mdio_o,
    output logic        mdio_t,
    input  logic        mdio_i,

    // ── PHY Reset ────────────────────────────────────────────────────
    output logic        phy_rstn,

    // ── Interrupt ─────────────────────────────────────────────────────
    output logic        irq,

    // ── Register Interface (AXI4-Lite subordinate, 6-bit addr) ────────
    // Write Address
    output logic        reg_axi_awready,
    input  logic        reg_axi_awvalid,
    input  logic [5:0]  reg_axi_awaddr,
    input  logic [2:0]  reg_axi_awprot,

    // Write Data
    output logic        reg_axi_wready,
    input  logic        reg_axi_wvalid,
    input  logic [31:0] reg_axi_wdata,
    input  logic [3:0]  reg_axi_wstrb,

    // Write Response
    input  logic        reg_axi_bready,
    output logic        reg_axi_bvalid,
    output logic [1:0]  reg_axi_bresp,

    // Read Address
    output logic        reg_axi_arready,
    input  logic        reg_axi_arvalid,
    input  logic [5:0]  reg_axi_araddr,
    input  logic [2:0]  reg_axi_arprot,

    // Read Data
    input  logic        reg_axi_rready,
    output logic        reg_axi_rvalid,
    output logic [31:0] reg_axi_rdata,
    output logic [1:0]  reg_axi_rresp
);

    // =====================================================================
    //  Constants
    // =====================================================================

    localparam int MDC_DIV = (CLK_FREQ_HZ / (2 * MDC_FREQ_HZ)) - 1;

    // =====================================================================
    //  Internal Control / Status signals (driven by register block)
    // =====================================================================

    logic        ctrl_go;
    logic        ctrl_wr_nrd;
    logic        ctrl_pre_dis;
    logic [4:0]  ctrl_prtad;
    logic [4:0]  ctrl_devad;
    logic [15:0] ctrl_reg_addr;
    logic [15:0] ctrl_wrdata;

    logic        status_busy;
    logic        status_done;
    logic        status_error;
    logic [15:0] captured_rddata;

    // =====================================================================
    //  AXI4-Lite Register Block (generated by PeakRDL)
    // =====================================================================

    axi_mdio_regs_pkg::axi_mdio_regs__in_t  regs_hwif_in;
    axi_mdio_regs_pkg::axi_mdio_regs__out_t regs_hwif_out;

    axi_mdio_regs u_regs (
        .clk            (clk),
        .rst            (rst),
        // AXI4-Lite — map reg_axi_* to s_axil_*
        .s_axil_awvalid (reg_axi_awvalid),
        .s_axil_awready (reg_axi_awready),
        .s_axil_awaddr  (reg_axi_awaddr),
        .s_axil_awprot  (reg_axi_awprot),
        .s_axil_wvalid  (reg_axi_wvalid),
        .s_axil_wready  (reg_axi_wready),
        .s_axil_wdata   (reg_axi_wdata),
        .s_axil_wstrb   (reg_axi_wstrb),
        .s_axil_bvalid  (reg_axi_bvalid),
        .s_axil_bready  (reg_axi_bready),
        .s_axil_bresp   (reg_axi_bresp),
        .s_axil_arvalid (reg_axi_arvalid),
        .s_axil_arready (reg_axi_arready),
        .s_axil_araddr  (reg_axi_araddr),
        .s_axil_arprot  (reg_axi_arprot),
        .s_axil_rvalid  (reg_axi_rvalid),
        .s_axil_rready  (reg_axi_rready),
        .s_axil_rdata   (reg_axi_rdata),
        .s_axil_rresp   (reg_axi_rresp),
        // Hardware interface
        .hwif_in        (regs_hwif_in),
        .hwif_out       (regs_hwif_out)
    );

    // Connect hwif_out → internal control signals
    assign ctrl_go       = regs_hwif_out.CTRL.go.value;
    assign ctrl_wr_nrd   = regs_hwif_out.CTRL.wr_nrd.value;
    assign ctrl_pre_dis  = regs_hwif_out.CTRL.pre_dis.value;
    assign ctrl_prtad    = regs_hwif_out.PHY_ADDR.prtad.value;
    assign ctrl_devad    = regs_hwif_out.PHY_ADDR.devad.value;
    assign ctrl_reg_addr = regs_hwif_out.REG_ADDR.addr.value;
    assign ctrl_wrdata   = regs_hwif_out.WRDATA.data.value;
    assign phy_rstn      = regs_hwif_out.PHY_RST.rstn.value;

    // Connect internal status signals → hwif_in
    assign regs_hwif_in.RDDATA.data.next       = captured_rddata;
    assign regs_hwif_in.STATUS.busy.next       = status_busy;
    assign regs_hwif_in.STATUS.done.hwset      = status_done;
    assign regs_hwif_in.STATUS.error.hwset     = status_error;
    assign regs_hwif_in.IRQ_STATUS.done.hwset  = status_done;
    assign regs_hwif_in.IRQ_STATUS.error.hwset = status_error;

    // =====================================================================
    //  Interrupt Output
    // =====================================================================

    assign irq = (regs_hwif_out.IRQ_STATUS.done.value  & regs_hwif_out.IRQ_EN.done_en.value)
               | (regs_hwif_out.IRQ_STATUS.error.value & regs_hwif_out.IRQ_EN.error_en.value);

    // =====================================================================
    //  MDC Clock Generation
    // =====================================================================

    logic [$clog2(MDC_DIV+1)-1:0] mdc_cnt;
    logic mdc_rise;
    logic mdc_fall;
    logic mdc_en;       // Gate MDC toggling — only active during transaction
    logic mdc_int;      // Internal MDC state

    always_ff @(posedge clk) begin
        if (rst) begin
            mdc_cnt  <= '0;
            mdc_int  <= 1'b0;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end else if (!mdc_en) begin
            mdc_cnt  <= '0;
            mdc_int  <= 1'b0;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end else if (mdc_cnt == MDC_DIV[$clog2(MDC_DIV+1)-1:0]) begin
            mdc_cnt  <= '0;
            mdc_int  <= ~mdc_int;
            mdc_rise <= ~mdc_int;
            mdc_fall <=  mdc_int;
        end else begin
            mdc_cnt  <= mdc_cnt + 1;
            mdc_rise <= 1'b0;
            mdc_fall <= 1'b0;
        end
    end

    assign mdc = mdc_int;

    // =====================================================================
    //  MDIO Clause 45 FSM
    // =====================================================================

    typedef enum logic [4:0] {
        ST_IDLE,
        ST_ADDR_PRE,
        ST_ADDR_ST,
        ST_ADDR_OP,
        ST_ADDR_PRTAD,
        ST_ADDR_DEVAD,
        ST_ADDR_TA,
        ST_ADDR_DATA,
        ST_TURNAROUND,
        ST_RW_PRE,
        ST_RW_ST,
        ST_RW_OP,
        ST_RW_PRTAD,
        ST_RW_DEVAD,
        ST_RW_TA,
        ST_RW_DATA,
        ST_TRAIL
    } mdio_state_t;

    mdio_state_t state, next_state;

    logic [5:0]  bit_cnt;
    logic [31:0] shift_reg;
    logic        is_write;     // Latched write/read direction
    logic        is_pre_dis;   // Latched preamble disable
    logic        ta_error;

    // ── Block 1: Sequential state register ───────────────────────────
    always_ff @(posedge clk) begin
        if (rst)
            state <= ST_IDLE;
        else
            state <= next_state;
    end

    // ── Block 2: Combinational next-state logic ──────────────────────
    always_comb begin
        next_state = state; // default: hold current state

        case (state)
            ST_IDLE: begin
                if (ctrl_go)
                    next_state = ctrl_pre_dis ? ST_ADDR_ST : ST_ADDR_PRE;
            end

            // ── Frame 1: Address Frame ───────────────────────────
            ST_ADDR_PRE: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_ST;
            end

            ST_ADDR_ST: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_OP;
            end

            ST_ADDR_OP: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_PRTAD;
            end

            ST_ADDR_PRTAD: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_DEVAD;
            end

            ST_ADDR_DEVAD: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_TA;
            end

            ST_ADDR_TA: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_ADDR_DATA;
            end

            ST_ADDR_DATA: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_TURNAROUND;
            end

            // ── Inter-frame gap ──────────────────────────────────
            ST_TURNAROUND: begin
                if (mdc_fall)
                    next_state = is_pre_dis ? ST_RW_ST : ST_RW_PRE;
            end

            // ── Frame 2: Read/Write Frame ────────────────────────
            ST_RW_PRE: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_RW_ST;
            end

            ST_RW_ST: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_RW_OP;
            end

            ST_RW_OP: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_RW_PRTAD;
            end

            ST_RW_PRTAD: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_RW_DEVAD;
            end

            ST_RW_DEVAD: begin
                if (mdc_fall && bit_cnt == 0)
                    next_state = ST_RW_TA;
            end

            ST_RW_TA: begin
                if (is_write) begin
                    if (mdc_fall && bit_cnt == 0)
                        next_state = ST_RW_DATA;
                end else begin
                    if (mdc_rise && bit_cnt == 0)
                        next_state = ST_RW_DATA;
                end
            end

            ST_RW_DATA: begin
                if (is_write) begin
                    if (mdc_fall && bit_cnt == 0)
                        next_state = ST_TRAIL;
                end else begin
                    if (mdc_rise && bit_cnt == 0)
                        next_state = ST_TRAIL;
                end
            end

            ST_TRAIL: begin
                if (mdc_fall)
                    next_state = ST_IDLE;
            end

            default: next_state = ST_IDLE;
        endcase
    end

    // ── Block 3: Sequential output / datapath logic ──────────────────
    // Cases on next_state so outputs are prepared for the incoming state.
    // Entry actions (state != next_state) set up the new field;
    // steady-state actions (state == next_state) perform shifting/sampling.
    always_ff @(posedge clk) begin
        // Default: clear single-cycle pulses
        status_done  <= 1'b0;
        status_error <= 1'b0;

        case (next_state)
                // ─────────────────────────────────────────────────────
                ST_IDLE: begin
                    if (state == ST_TRAIL) begin
                        // Trailing cycle complete — stop clock
                        mdc_en      <= 1'b0;
                    end else begin
                        // Steady-state idle
                        mdio_t      <= 1'b1;
                        mdio_o      <= 1'b1;
                        mdc_en      <= 1'b0;
                        status_busy <= 1'b0;
                    end
                end

                // ── Frame 1: Address Frame ───────────────────────────
                ST_ADDR_PRE: begin
                    if (state == ST_IDLE) begin
                        // Entry: load preamble (32 ones)
                        is_write    <= ctrl_wr_nrd;
                        is_pre_dis  <= ctrl_pre_dis;
                        ta_error    <= 1'b0;
                        status_busy <= 1'b1;
                        shift_reg   <= 32'hFFFF_FFFF;
                        bit_cnt     <= 6'd31;
                        mdio_t      <= 1'b0;
                        mdio_o    <= 1'b1;
                        mdc_en      <= 1'b1;
                    end else if (mdc_fall) begin
                        // Shifting preamble
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_ST: begin
                    if (state == ST_IDLE) begin
                        // Entry (preamble disabled): init and load ST = 2'b00
                        is_write    <= ctrl_wr_nrd;
                        is_pre_dis  <= ctrl_pre_dis;
                        ta_error    <= 1'b0;
                        status_busy <= 1'b1;
                        mdc_en      <= 1'b1;
                        mdio_t      <= 1'b0;
                        mdio_o    <= 1'b0;
                        shift_reg   <= {2'b00, 30'd0};
                        bit_cnt     <= 6'd1;
                    end else if (state == ST_ADDR_PRE) begin
                        // Entry: output last preamble bit, load ST = 2'b00
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {2'b00, 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_OP: begin
                    if (state == ST_ADDR_ST) begin
                        // Entry: output last ST bit, load OP = 2'b00 (address)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {2'b00, 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_PRTAD: begin
                    if (state == ST_ADDR_OP) begin
                        // Entry: output last OP bit, load PRTAD (5 bits)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {ctrl_prtad, 27'd0};
                        bit_cnt   <= 6'd4;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_DEVAD: begin
                    if (state == ST_ADDR_PRTAD) begin
                        // Entry: output last PRTAD bit, load DEVAD (5 bits)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {ctrl_devad, 27'd0};
                        bit_cnt   <= 6'd4;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_TA: begin
                    if (state == ST_ADDR_DEVAD) begin
                        // Entry: output last DEVAD bit, load TA = 2'b10
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {2'b10, 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_ADDR_DATA: begin
                    if (state == ST_ADDR_TA) begin
                        // Entry: output last TA bit, load REG_ADDR (16 bits)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {ctrl_reg_addr, 16'd0};
                        bit_cnt   <= 6'd15;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                // ── Inter-frame gap ──────────────────────────────────
                ST_TURNAROUND: begin
                    if (state == ST_ADDR_DATA) begin
                        // Entry: output last addr data bit, release bus
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        mdio_t    <= 1'b1;
                    end
                    // Steady-state: wait for mdc_fall (no outputs to drive)
                end

                // ── Frame 2: Read/Write Frame ────────────────────────
                ST_RW_PRE: begin
                    if (state == ST_TURNAROUND) begin
                        // Entry: load preamble for frame 2 (32 ones)
                        shift_reg <= 32'hFFFF_FFFF;
                        bit_cnt   <= 6'd31;
                        mdio_t    <= 1'b0;
                        mdio_o  <= 1'b1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_RW_ST: begin
                    if (state == ST_TURNAROUND) begin
                        // Entry (preamble disabled): load ST = 2'b00
                        mdio_t    <= 1'b0;
                        mdio_o  <= 1'b0;
                        shift_reg <= {2'b00, 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (state == ST_RW_PRE) begin
                        // Entry: output last preamble bit, load ST = 2'b00
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {2'b00, 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_RW_OP: begin
                    if (state == ST_RW_ST) begin
                        // Entry: output last ST bit, load OP
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {(is_write ? 2'b01 : 2'b11), 30'd0};
                        bit_cnt   <= 6'd1;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_RW_PRTAD: begin
                    if (state == ST_RW_OP) begin
                        // Entry: output last OP bit, load PRTAD (5 bits)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {ctrl_prtad, 27'd0};
                        bit_cnt   <= 6'd4;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_RW_DEVAD: begin
                    if (state == ST_RW_PRTAD) begin
                        // Entry: output last PRTAD bit, load DEVAD (5 bits)
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {ctrl_devad, 27'd0};
                        bit_cnt   <= 6'd4;
                    end else if (mdc_fall) begin
                        mdio_o  <= shift_reg[31];
                        shift_reg <= {shift_reg[30:0], 1'b0};
                        bit_cnt   <= bit_cnt - 1;
                    end
                end

                ST_RW_TA: begin
                    if (state == ST_RW_DEVAD) begin
                        // Entry: output last DEVAD bit, set up TA
                        mdio_o <= shift_reg[31];
                        if (is_write) begin
                            // Write TA = 2'b10, we drive
                            shift_reg <= {2'b10, 30'd0};
                            bit_cnt   <= 6'd1;
                            mdio_t    <= 1'b0;
                        end else begin
                            // Read TA: release bus, PHY drives
                            shift_reg <= '0;
                            bit_cnt   <= 6'd1;
                            mdio_t    <= 1'b1;
                        end
                    end else if (is_write) begin
                        // Write TA: shift out 1 then 0
                        if (mdc_fall) begin
                            mdio_o  <= shift_reg[31];
                            shift_reg <= {shift_reg[30:0], 1'b0};
                            bit_cnt   <= bit_cnt - 1;
                        end
                    end else begin
                        // Read TA: wait for PHY
                        if (mdc_rise)
                            bit_cnt <= bit_cnt - 1;
                    end
                end

                ST_RW_DATA: begin
                    if (state == ST_RW_TA) begin
                        // Entry from TA phase
                        if (is_write) begin
                            // Output last TA bit, load write data (16 bits)
                            mdio_o  <= shift_reg[31];
                            shift_reg <= {ctrl_wrdata, 16'd0};
                            bit_cnt   <= 6'd15;
                        end else begin
                            // Second TA bit — PHY should drive 0
                            if (mdio_i != 1'b0)
                                ta_error <= 1'b1;
                            bit_cnt <= 6'd15;
                        end
                    end else if (is_write) begin
                        // Write: shift out data on falling edge
                        if (mdc_fall) begin
                            mdio_o  <= shift_reg[31];
                            shift_reg <= {shift_reg[30:0], 1'b0};
                            bit_cnt   <= bit_cnt - 1;
                        end
                    end else begin
                        // Read: shift in data on rising edge
                        if (mdc_rise) begin
                            captured_rddata <= {captured_rddata[14:0], mdio_i};
                            bit_cnt         <= bit_cnt - 1;
                        end
                    end
                end

                ST_TRAIL: begin
                    if (state == ST_RW_DATA) begin
                        // Entry: finish last bit, release bus, signal done
                        status_busy <= 1'b0;
                        status_done <= 1'b1;
                        mdio_t      <= 1'b1;
                        if (is_write) begin
                            mdio_o    <= shift_reg[31];
                            shift_reg <= {shift_reg[30:0], 1'b0};
                        end else begin
                            captured_rddata <= {captured_rddata[14:0], mdio_i};
                            status_error    <= ta_error;
                        end
                    end
                    // MDC keeps running; ST_IDLE entry will stop it
                end

                default: ;
            endcase
    end

endmodule
