// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module axi_mdio_regs (
        input wire clk,
        input wire rst,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [5:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [5:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input axi_mdio_regs_pkg::axi_mdio_regs__in_t hwif_in,
        output axi_mdio_regs_pkg::axi_mdio_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [5:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [5:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(rst) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[5:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[5:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[5:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [31:0] rdata;
    } axil_resp_buffer[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(rst) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[0:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[0:0]].is_wr) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer[axil_resp_rptr[0:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[0:0]].err) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CTRL;
        logic PHY_ADDR;
        logic REG_ADDR;
        logic WRDATA;
        logic RDDATA;
        logic STATUS;
        logic IRQ_STATUS;
        logic IRQ_EN;
        logic PHY_RST;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '0;
        is_invalid_rw = '0;
        decoded_reg_strb.CTRL = cpuif_req_masked & (cpuif_addr == 6'h0);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.PHY_ADDR = cpuif_req_masked & (cpuif_addr == 6'h4);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.REG_ADDR = cpuif_req_masked & (cpuif_addr == 6'h8);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.WRDATA = cpuif_req_masked & (cpuif_addr == 6'hc);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.RDDATA = cpuif_req_masked & (cpuif_addr == 6'h10) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 6'h14) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h14);
        decoded_reg_strb.IRQ_STATUS = cpuif_req_masked & (cpuif_addr == 6'h18);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.IRQ_EN = cpuif_req_masked & (cpuif_addr == 6'h1c);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h1c);
        decoded_reg_strb.PHY_RST = cpuif_req_masked & (cpuif_addr == 6'h20);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 6'h20);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } go;
            struct {
                logic next;
                logic load_next;
            } wr_nrd;
            struct {
                logic next;
                logic load_next;
            } pre_dis;
        } CTRL;
        struct {
            struct {
                logic [4:0] next;
                logic load_next;
            } prtad;
            struct {
                logic [4:0] next;
                logic load_next;
            } devad;
        } PHY_ADDR;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } addr;
        } REG_ADDR;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } data;
        } WRDATA;
        struct {
            struct {
                logic next;
                logic load_next;
            } done;
            struct {
                logic next;
                logic load_next;
            } error;
        } STATUS;
        struct {
            struct {
                logic next;
                logic load_next;
            } done;
            struct {
                logic next;
                logic load_next;
            } error;
        } IRQ_STATUS;
        struct {
            struct {
                logic next;
                logic load_next;
            } done_en;
            struct {
                logic next;
                logic load_next;
            } error_en;
        } IRQ_EN;
        struct {
            struct {
                logic next;
                logic load_next;
            } rstn;
        } PHY_RST;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } go;
            struct {
                logic value;
            } wr_nrd;
            struct {
                logic value;
            } pre_dis;
        } CTRL;
        struct {
            struct {
                logic [4:0] value;
            } prtad;
            struct {
                logic [4:0] value;
            } devad;
        } PHY_ADDR;
        struct {
            struct {
                logic [15:0] value;
            } addr;
        } REG_ADDR;
        struct {
            struct {
                logic [15:0] value;
            } data;
        } WRDATA;
        struct {
            struct {
                logic value;
            } done;
            struct {
                logic value;
            } error;
        } STATUS;
        struct {
            struct {
                logic value;
            } done;
            struct {
                logic value;
            } error;
        } IRQ_STATUS;
        struct {
            struct {
                logic value;
            } done_en;
            struct {
                logic value;
            } error_en;
        } IRQ_EN;
        struct {
            struct {
                logic value;
            } rstn;
        } PHY_RST;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: axi_mdio_regs.CTRL.go
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.go.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.go.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.CTRL.go.next = next_c;
        field_combo.CTRL.go.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.go.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.go.load_next) begin
                field_storage.CTRL.go.value <= field_combo.CTRL.go.next;
            end
        end
    end
    assign hwif_out.CTRL.go.value = field_storage.CTRL.go.value;
    // Field: axi_mdio_regs.CTRL.wr_nrd
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.wr_nrd.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.wr_nrd.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.CTRL.wr_nrd.next = next_c;
        field_combo.CTRL.wr_nrd.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.wr_nrd.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.wr_nrd.load_next) begin
                field_storage.CTRL.wr_nrd.value <= field_combo.CTRL.wr_nrd.next;
            end
        end
    end
    assign hwif_out.CTRL.wr_nrd.value = field_storage.CTRL.wr_nrd.value;
    // Field: axi_mdio_regs.CTRL.pre_dis
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.pre_dis.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.pre_dis.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.CTRL.pre_dis.next = next_c;
        field_combo.CTRL.pre_dis.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.pre_dis.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.pre_dis.load_next) begin
                field_storage.CTRL.pre_dis.value <= field_combo.CTRL.pre_dis.next;
            end
        end
    end
    assign hwif_out.CTRL.pre_dis.value = field_storage.CTRL.pre_dis.value;
    // Field: axi_mdio_regs.PHY_ADDR.prtad
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PHY_ADDR.prtad.value;
        load_next_c = '0;
        if(decoded_reg_strb.PHY_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PHY_ADDR.prtad.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.PHY_ADDR.prtad.next = next_c;
        field_combo.PHY_ADDR.prtad.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PHY_ADDR.prtad.value <= 5'h0;
        end else begin
            if(field_combo.PHY_ADDR.prtad.load_next) begin
                field_storage.PHY_ADDR.prtad.value <= field_combo.PHY_ADDR.prtad.next;
            end
        end
    end
    assign hwif_out.PHY_ADDR.prtad.value = field_storage.PHY_ADDR.prtad.value;
    // Field: axi_mdio_regs.PHY_ADDR.devad
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PHY_ADDR.devad.value;
        load_next_c = '0;
        if(decoded_reg_strb.PHY_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PHY_ADDR.devad.value & ~decoded_wr_biten[12:8]) | (decoded_wr_data[12:8] & decoded_wr_biten[12:8]);
            load_next_c = '1;
        end
        field_combo.PHY_ADDR.devad.next = next_c;
        field_combo.PHY_ADDR.devad.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PHY_ADDR.devad.value <= 5'h0;
        end else begin
            if(field_combo.PHY_ADDR.devad.load_next) begin
                field_storage.PHY_ADDR.devad.value <= field_combo.PHY_ADDR.devad.next;
            end
        end
    end
    assign hwif_out.PHY_ADDR.devad.value = field_storage.PHY_ADDR.devad.value;
    // Field: axi_mdio_regs.REG_ADDR.addr
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.REG_ADDR.addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.REG_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.REG_ADDR.addr.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.REG_ADDR.addr.next = next_c;
        field_combo.REG_ADDR.addr.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.REG_ADDR.addr.value <= 16'h0;
        end else begin
            if(field_combo.REG_ADDR.addr.load_next) begin
                field_storage.REG_ADDR.addr.value <= field_combo.REG_ADDR.addr.next;
            end
        end
    end
    assign hwif_out.REG_ADDR.addr.value = field_storage.REG_ADDR.addr.value;
    // Field: axi_mdio_regs.WRDATA.data
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.WRDATA.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.WRDATA && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.WRDATA.data.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.WRDATA.data.next = next_c;
        field_combo.WRDATA.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.WRDATA.data.value <= 16'h0;
        end else begin
            if(field_combo.WRDATA.data.load_next) begin
                field_storage.WRDATA.data.value <= field_combo.WRDATA.data.next;
            end
        end
    end
    assign hwif_out.WRDATA.data.value = field_storage.WRDATA.data.value;
    // Field: axi_mdio_regs.STATUS.done
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.done.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.STATUS.done.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.STATUS.done.next = next_c;
        field_combo.STATUS.done.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.done.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.done.load_next) begin
                field_storage.STATUS.done.value <= field_combo.STATUS.done.next;
            end
        end
    end
    assign hwif_out.STATUS.done.value = field_storage.STATUS.done.value;
    // Field: axi_mdio_regs.STATUS.error
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.error.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && !decoded_req_is_wr) begin // SW clear on read
            next_c = '0;
            load_next_c = '1;
        end else if(hwif_in.STATUS.error.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.STATUS.error.next = next_c;
        field_combo.STATUS.error.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.error.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.error.load_next) begin
                field_storage.STATUS.error.value <= field_combo.STATUS.error.next;
            end
        end
    end
    assign hwif_out.STATUS.error.value = field_storage.STATUS.error.value;
    // Field: axi_mdio_regs.IRQ_STATUS.done
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_STATUS.done.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ_STATUS.done.value & ~(decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.IRQ_STATUS.done.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.IRQ_STATUS.done.next = next_c;
        field_combo.IRQ_STATUS.done.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_STATUS.done.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_STATUS.done.load_next) begin
                field_storage.IRQ_STATUS.done.value <= field_combo.IRQ_STATUS.done.next;
            end
        end
    end
    assign hwif_out.IRQ_STATUS.done.value = field_storage.IRQ_STATUS.done.value;
    // Field: axi_mdio_regs.IRQ_STATUS.error
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_STATUS.error.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ_STATUS.error.value & ~(decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else if(hwif_in.IRQ_STATUS.error.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end
        field_combo.IRQ_STATUS.error.next = next_c;
        field_combo.IRQ_STATUS.error.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_STATUS.error.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_STATUS.error.load_next) begin
                field_storage.IRQ_STATUS.error.value <= field_combo.IRQ_STATUS.error.next;
            end
        end
    end
    assign hwif_out.IRQ_STATUS.error.value = field_storage.IRQ_STATUS.error.value;
    // Field: axi_mdio_regs.IRQ_EN.done_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.done_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.done_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.done_en.next = next_c;
        field_combo.IRQ_EN.done_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.done_en.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.done_en.load_next) begin
                field_storage.IRQ_EN.done_en.value <= field_combo.IRQ_EN.done_en.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.done_en.value = field_storage.IRQ_EN.done_en.value;
    // Field: axi_mdio_regs.IRQ_EN.error_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.error_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.error_en.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.error_en.next = next_c;
        field_combo.IRQ_EN.error_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.error_en.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.error_en.load_next) begin
                field_storage.IRQ_EN.error_en.value <= field_combo.IRQ_EN.error_en.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.error_en.value = field_storage.IRQ_EN.error_en.value;
    // Field: axi_mdio_regs.PHY_RST.rstn
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PHY_RST.rstn.value;
        load_next_c = '0;
        if(decoded_reg_strb.PHY_RST && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PHY_RST.rstn.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.PHY_RST.rstn.next = next_c;
        field_combo.PHY_RST.rstn.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PHY_RST.rstn.value <= 1'h0;
        end else begin
            if(field_combo.PHY_RST.rstn.load_next) begin
                field_storage.PHY_RST.rstn.value <= field_combo.PHY_RST.rstn.next;
            end
        end
    end
    assign hwif_out.PHY_RST.rstn.value = field_storage.PHY_RST.rstn.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = decoded_err;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[9];
    assign readback_array[0][0:0] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.go.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.wr_nrd.value : '0;
    assign readback_array[0][2:2] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.pre_dis.value : '0;
    assign readback_array[0][31:3] = '0;
    assign readback_array[1][4:0] = (decoded_reg_strb.PHY_ADDR && !decoded_req_is_wr) ? field_storage.PHY_ADDR.prtad.value : '0;
    assign readback_array[1][7:5] = (decoded_reg_strb.PHY_ADDR && !decoded_req_is_wr) ? 3'h0 : '0;
    assign readback_array[1][12:8] = (decoded_reg_strb.PHY_ADDR && !decoded_req_is_wr) ? field_storage.PHY_ADDR.devad.value : '0;
    assign readback_array[1][31:13] = '0;
    assign readback_array[2][15:0] = (decoded_reg_strb.REG_ADDR && !decoded_req_is_wr) ? field_storage.REG_ADDR.addr.value : '0;
    assign readback_array[2][31:16] = '0;
    assign readback_array[3][15:0] = (decoded_reg_strb.WRDATA && !decoded_req_is_wr) ? field_storage.WRDATA.data.value : '0;
    assign readback_array[3][31:16] = '0;
    assign readback_array[4][15:0] = (decoded_reg_strb.RDDATA && !decoded_req_is_wr) ? hwif_in.RDDATA.data.next : '0;
    assign readback_array[4][31:16] = '0;
    assign readback_array[5][0:0] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? hwif_in.STATUS.busy.next : '0;
    assign readback_array[5][1:1] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? field_storage.STATUS.done.value : '0;
    assign readback_array[5][2:2] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? field_storage.STATUS.error.value : '0;
    assign readback_array[5][31:3] = '0;
    assign readback_array[6][0:0] = (decoded_reg_strb.IRQ_STATUS && !decoded_req_is_wr) ? field_storage.IRQ_STATUS.done.value : '0;
    assign readback_array[6][1:1] = (decoded_reg_strb.IRQ_STATUS && !decoded_req_is_wr) ? field_storage.IRQ_STATUS.error.value : '0;
    assign readback_array[6][31:2] = '0;
    assign readback_array[7][0:0] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.done_en.value : '0;
    assign readback_array[7][1:1] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.error_en.value : '0;
    assign readback_array[7][31:2] = '0;
    assign readback_array[8][0:0] = (decoded_reg_strb.PHY_RST && !decoded_req_is_wr) ? field_storage.PHY_RST.rstn.value : '0;
    assign readback_array[8][31:1] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = decoded_err;
        readback_data_var = '0;
        for(int i=0; i<9; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
