// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package axi_mdio_regs_pkg;

    localparam AXI_MDIO_REGS_DATA_WIDTH = 32;
    localparam AXI_MDIO_REGS_MIN_ADDR_WIDTH = 5;
    localparam AXI_MDIO_REGS_SIZE = 'h20;

    typedef struct {
        logic [15:0] next;
    } axi_mdio_regs__rddata_reg__data__in_t;

    typedef struct {
        axi_mdio_regs__rddata_reg__data__in_t data;
    } axi_mdio_regs__rddata_reg__in_t;

    typedef struct {
        logic next;
    } axi_mdio_regs__status_reg__busy__in_t;

    typedef struct {
        logic hwset;
    } axi_mdio_regs__status_reg__done__in_t;

    typedef struct {
        logic hwset;
    } axi_mdio_regs__status_reg__error__in_t;

    typedef struct {
        axi_mdio_regs__status_reg__busy__in_t busy;
        axi_mdio_regs__status_reg__done__in_t done;
        axi_mdio_regs__status_reg__error__in_t error;
    } axi_mdio_regs__status_reg__in_t;

    typedef struct {
        logic hwset;
    } axi_mdio_regs__irq_status_reg__done__in_t;

    typedef struct {
        logic hwset;
    } axi_mdio_regs__irq_status_reg__error__in_t;

    typedef struct {
        axi_mdio_regs__irq_status_reg__done__in_t done;
        axi_mdio_regs__irq_status_reg__error__in_t error;
    } axi_mdio_regs__irq_status_reg__in_t;

    typedef struct {
        axi_mdio_regs__rddata_reg__in_t RDDATA;
        axi_mdio_regs__status_reg__in_t STATUS;
        axi_mdio_regs__irq_status_reg__in_t IRQ_STATUS;
    } axi_mdio_regs__in_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__ctrl_reg__go__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__ctrl_reg__wr_nrd__out_t;

    typedef struct {
        axi_mdio_regs__ctrl_reg__go__out_t go;
        axi_mdio_regs__ctrl_reg__wr_nrd__out_t wr_nrd;
    } axi_mdio_regs__ctrl_reg__out_t;

    typedef struct {
        logic [4:0] value;
    } axi_mdio_regs__phy_addr_reg__prtad__out_t;

    typedef struct {
        logic [4:0] value;
    } axi_mdio_regs__phy_addr_reg__devad__out_t;

    typedef struct {
        axi_mdio_regs__phy_addr_reg__prtad__out_t prtad;
        axi_mdio_regs__phy_addr_reg__devad__out_t devad;
    } axi_mdio_regs__phy_addr_reg__out_t;

    typedef struct {
        logic [15:0] value;
    } axi_mdio_regs__reg_addr_reg__addr__out_t;

    typedef struct {
        axi_mdio_regs__reg_addr_reg__addr__out_t addr;
    } axi_mdio_regs__reg_addr_reg__out_t;

    typedef struct {
        logic [15:0] value;
    } axi_mdio_regs__wrdata_reg__data__out_t;

    typedef struct {
        axi_mdio_regs__wrdata_reg__data__out_t data;
    } axi_mdio_regs__wrdata_reg__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__status_reg__done__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__status_reg__error__out_t;

    typedef struct {
        axi_mdio_regs__status_reg__done__out_t done;
        axi_mdio_regs__status_reg__error__out_t error;
    } axi_mdio_regs__status_reg__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__irq_status_reg__done__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__irq_status_reg__error__out_t;

    typedef struct {
        axi_mdio_regs__irq_status_reg__done__out_t done;
        axi_mdio_regs__irq_status_reg__error__out_t error;
    } axi_mdio_regs__irq_status_reg__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__irq_en_reg__done_en__out_t;

    typedef struct {
        logic value;
    } axi_mdio_regs__irq_en_reg__error_en__out_t;

    typedef struct {
        axi_mdio_regs__irq_en_reg__done_en__out_t done_en;
        axi_mdio_regs__irq_en_reg__error_en__out_t error_en;
    } axi_mdio_regs__irq_en_reg__out_t;

    typedef struct {
        axi_mdio_regs__ctrl_reg__out_t CTRL;
        axi_mdio_regs__phy_addr_reg__out_t PHY_ADDR;
        axi_mdio_regs__reg_addr_reg__out_t REG_ADDR;
        axi_mdio_regs__wrdata_reg__out_t WRDATA;
        axi_mdio_regs__status_reg__out_t STATUS;
        axi_mdio_regs__irq_status_reg__out_t IRQ_STATUS;
        axi_mdio_regs__irq_en_reg__out_t IRQ_EN;
    } axi_mdio_regs__out_t;
endpackage
